spring:
  config:
    activate:
      on-profile: qa

# To get property value using @Value("${build.version}")
build:
  version: 2.0.0

accounts:
  environment: DEFAULT - QA
  developer:
    name: Jay Oswal - QA
    location: HQ
  email: test@mail.com
  contact:
    - 12345
    - 67890