spring:
  application:
    name=accounts

  config:
    import:
      - "cards-qa.yaml"
      - "cards-prod.yaml"
  profiles:
    active:
      - default

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''

  h2:
    console:
      enables: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8080
  shutdown: graceful


# To get property value using @Value("${build.version}")
build:
  version: 1.0.0

accounts:
  environment: DEFAULT - DEV
  developer:
    name: Jay Oswal - DEV
    location: HQ
  email: test@mail.com
  contact:
    - 12345
    - 67890


