spring:
  config:
    activate:
      on-profile: qa

build:
  version: 2.0.0

cards:
  environment: QA
  developer:
    name: Jay Oswal - QA
    location: HQ
  email: test@mail.com
  contact:
    - 12345
    - 67890