spring:
  config:
    activate:
      on-profile: prod

build:
  version: 3.0.0

cards:
  environment: PROD
  developer:
    name: Jay Oswal - PROD
    location: HQ
  email: test@mail.com
  contact:
    - 12345
    - 67890