spring:

  application:
    name: cards

  profiles:
    active:
      - prod

  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}

server:
  port: 9000
  shutdown: graceful


